### ISSUE TITLE
Illegal Authentication

### ISSUE THREAD

**Issue by leechenghan** [leonnnn/python3-simplepam#2]
simplepam still authenticates if you type in a password which starts with the correct password

Say your password is 'foo'. If you type in 'foobar', it still authenticates.

Is anyone else experiencing this issue?

**Comment by leonnnn** [comment]
I’m unable to reproduce.  I’ve set the password of a test account to ‘foo’, simplepam authenticates fine when entering ‘foo’, but fails to authenticate when entering ‘foobar’ (or any other sequence I’ve tested).

I’ve tested both python 3 and python 2.

Can you double-check and, if you still see the reported behaviour, elaborate a bit more on your test circumstances and methodology?

**Comment by leechenghan** [comment]
Just found out that the issue is with what Linux uses for authentication. It only grabs the first 8 characters. Thanks for your help!
